# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: closure.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='closure.proto',
  package='closure',
  serialized_pb=_b('\n\rclosure.proto\x12\x07\x63losure\"\xab\x01\n\tPartition\x12(\n\x06tracks\x18\x01 \x03(\x0b\x32\x18.closure.Partition.Track\x1at\n\x05Track\x12,\n\x05views\x18\x01 \x03(\x0b\x32\x1d.closure.Partition.Track.View\x1a=\n\x04View\x12\r\n\x05image\x18\x01 \x02(\x05\x12\x10\n\x08keypoint\x18\x02 \x02(\x05\x12\t\n\x01u\x18\x03 \x02(\x02\x12\t\n\x01v\x18\x04 \x02(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PARTITION_TRACK_VIEW = _descriptor.Descriptor(
  name='View',
  full_name='closure.Partition.Track.View',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='closure.Partition.Track.View.image', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keypoint', full_name='closure.Partition.Track.View.keypoint', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u', full_name='closure.Partition.Track.View.u', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v', full_name='closure.Partition.Track.View.v', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=198,
)

_PARTITION_TRACK = _descriptor.Descriptor(
  name='Track',
  full_name='closure.Partition.Track',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='views', full_name='closure.Partition.Track.views', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PARTITION_TRACK_VIEW, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=198,
)

_PARTITION = _descriptor.Descriptor(
  name='Partition',
  full_name='closure.Partition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tracks', full_name='closure.Partition.tracks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PARTITION_TRACK, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=198,
)

_PARTITION_TRACK_VIEW.containing_type = _PARTITION_TRACK
_PARTITION_TRACK.fields_by_name['views'].message_type = _PARTITION_TRACK_VIEW
_PARTITION_TRACK.containing_type = _PARTITION
_PARTITION.fields_by_name['tracks'].message_type = _PARTITION_TRACK
DESCRIPTOR.message_types_by_name['Partition'] = _PARTITION

Partition = _reflection.GeneratedProtocolMessageType('Partition', (_message.Message,), dict(

  Track = _reflection.GeneratedProtocolMessageType('Track', (_message.Message,), dict(

    View = _reflection.GeneratedProtocolMessageType('View', (_message.Message,), dict(
      DESCRIPTOR = _PARTITION_TRACK_VIEW,
      __module__ = 'closure_pb2'
      # @@protoc_insertion_point(class_scope:closure.Partition.Track.View)
      ))
    ,
    DESCRIPTOR = _PARTITION_TRACK,
    __module__ = 'closure_pb2'
    # @@protoc_insertion_point(class_scope:closure.Partition.Track)
    ))
  ,
  DESCRIPTOR = _PARTITION,
  __module__ = 'closure_pb2'
  # @@protoc_insertion_point(class_scope:closure.Partition)
  ))
_sym_db.RegisterMessage(Partition)
_sym_db.RegisterMessage(Partition.Track)
_sym_db.RegisterMessage(Partition.Track.View)


# @@protoc_insertion_point(module_scope)
